services:
- type: web
  name: telegram-webhook
  runtime: python
  repo: https://github.com/nailydragon/telegram-webhook
  plan: free
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
version: "1"
